#!/bin/sh

# Enable debugging, useful when you want to figure out why
# this script is not behaving the way you expect it to do
DEBUG=0

# What do you want to call this service?
SERVICE_NAME="Factorio"

# Which user/group is running factorio?
# Running any public service as "root" is generally not recommended
F_USER=factorio
F_GROUP=factorio

# The absolute path to the factorio server directory inside the container
FACTORIO_PATH="/srv/dockerized-factorio/server"
# Server settings file
SERVER_SETTINGS="${FACTORIO_PATH}/data/server-settings.json"

# Port on which you want to run the server
PORT=34197

# Save the command/chat/log on server start? Default location /srv/factorio/server.out
# Setting this to 0 will cause the script to erase the log file on each start
# If you set this to 1 you might want to apply logrotate on the log or it will eventually fill your disk
SAVELOG=0

# Extras
# Additional binary arguments, these will be sent to the binary when issuing the "start" command
EXTRA_BINARGS=""

BINARY="${FACTORIO_PATH}/bin/x64/factorio"